[package]
name = "model"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = "7.2.0"
redis = "0.21"
serde_json = "1.0.68"
serde = { version = "1.0", features = ["derive"] }
serde_utils = {path = "../serde_utils"}
uuid = { version = "0.8", features = ["serde", "v4"] }
void = "1.0"
errors = {path = "../errors"}

