[package]
name = "tx_endpoint"
version = "0.1.0"
edition = "2018"
authors = ["David Skyberg <davidskyberg@gmail.com>"]
repository = "https://github.com/dskyberg/gnap"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
mongodb = "2.0.0"
redis = { version = "0.21", features = ["tokio-comp", "connection-manager"]}
pretty_env_logger = "0.4.0"
serde_json = "1.0.68"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.29"
warp = "0.3.1"
futures = "0.3.17"
log4rs = "1.0.0"
log = "0.4.14"
jsonwebtoken = "7.2.0"
tokio = { version = "1.12.0", features = ["full"] }
errors = {path = "../errors"}
model = {path = "../model"}
dao = {path = "../dao"}
